### ISSUE TITLE
Attempting to run the tool results in a syntax error

### ISSUE THREAD

**Issue by ragunathjawahar** [pinterest/git-stacktrace#37]
I tried running the tool on a Ubuntu vagrant box and an Alpine docker container, however both resulted in the following error.

**Trace**
```
Traceback (most recent call last):
  File "/home/vagrant/.local/bin/git-stacktrace", line 7, in <module>
    from git_stacktrace.cmd import main
  File "/home/vagrant/.local/lib/python2.7/site-packages/git_stacktrace/cmd.py", line 10, in <module>
    from git_stacktrace import api
  File "/home/vagrant/.local/lib/python2.7/site-packages/git_stacktrace/api.py", line 22, in <module>
    from git_stacktrace import parse_trace
  File "/home/vagrant/.local/lib/python2.7/site-packages/git_stacktrace/parse_trace.py", line 38
    class Traceback(object, metaclass=abc.ABCMeta):
                                     ^
SyntaxError: invalid syntax
```

**Environment 1 (Vagrant)**
- git version 2.17.1
- Python 2.7.17
- pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
- No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

**Environment 2 (Docker)**
- Alpine Linux 3.13.6
- Docker version 20.10.8, build 3967b7d

**Comment by ragunathjawahar** [comment]
Closing this. Resolved after using Python 3.
